library(tabulizer)
library(tesseract)


file_path_gb <-
  '/Users/Constanze/Desktop/uni/ba arbeit/sentiment analysis/Berichte/geschäftsberichte'
file_names_gb <-
  file.path(file_path_gb, list.files(file_path_gb), sep = '/')


#CEO LETTERS
einsundeins_gb_ceo <-extract_text(file = file_names_gb[1], pages = 4:7)
schaeffler_gb_ceo <-extract_text(file = file_names_gb[2], pages = 13:15)
aurubis_gb_ceo <- extract_text(file = file_names_gb[3], pages = 7:8)
axelspringer_gb_ceo <- extract_text(file = file_names_gb[5], pages = 4:5)
bechtle_gb_ceo <- extract_text(file = file_names_gb[6], pages = 10:11)
brenntag_gb_ceo <- extract_text(file = file_names_gb[7], pages = 7)
commerzbank_gb_ceo <- extract_text(file = file_names_gb[8], pages = 4:6)
ctseventim_gb_ceo <- extract_text(file = file_names_gb[9], pages = 6:8)
deliveryhero_gb_ceo <- extract_text(file = file_names_gb[10], pages = 4:7)
deutscheeuroshop_gb_ceo <- extract_text(file = file_names_gb[11], pages = 6:10)
deutschepfandbriefbank_gb_ceo <- extract_text(file = file_names_gb[12], pages = 5)
deutschewohnen_gb_ceo <- extract_text(file = file_names_gb[13], pages = 9)
duerr_gb_ceo <- extract_text(file = file_names_gb[14], pages = 8:11)
evonik_gb_ceo <- extract_text(file = file_names_gb[15], pages = 6:7)
evotec_gb_ceo <- extract_text(file = file_names_gb[16], pages = 3:4)
fielmann_gb_ceo <- extract_text(file = file_names_gb[17], pages = 9:11)
fraport_gb_ceo <- extract_text(file = file_names_gb[18], pages = 5:7)
freenet_gb_ceo <- extract_text(file = file_names_gb[19], pages = 22:27)
fuchs_gb_ceo <- extract_text(file = file_names_gb[20], pages = 10:13)
gea_gb_ceo <- extract_text(file = file_names_gb[21], pages = 14:15)
gerresheimer_gb_ceo <- extract_text(file = file_names_gb[22], pages = 7:11)
hannoverrueck_gb_ceo <- extract_text(file = file_names_gb[23], pages = 6:9)
hella_gb_ceo <- extract_text(file = file_names_gb[24], pages = 9:11)
hochtief_gb_ceo <- extract_text(file = file_names_gb[25], pages = 9:11)
hugoboss_gb_ceo <- extract_text(file = file_names_gb[26], pages = 5:7)
innogy_gb_ceo <- extract_text(file = file_names_gb[27], pages = 5)
kunds_gb_ceo <- extract_text(file = file_names_gb[28], pages = 7:9)
kion_gb_ceo <- extract_text(file = file_names_gb[29], pages = 10:15)
lanxess_gb_ceo <- extract_text(file = file_names_gb[30], pages = 6)
legimmobilien_gb_ceo <- extract_text(file = file_names_gb[31], pages = 7:9)
metro_gb_ceo <- extract_text(file = file_names_gb[32], pages = 7:11)
morphosys_gb_ceo <- extract_text(file = file_names_gb[33], pages = 20:25)
mtuaerosystems_gb_ceo <- extract_text(file = file_names_gb[34], pages = 36:37)
nemetschek_gb_ceo <- extract_text(file = file_names_gb[35], pages = 20:23)
norma_gb_ceo <- extract_text(file = file_names_gb[36], pages = 13:14)
p7s1_gb_ceo <- extract_text(file = file_names_gb[38], pages = 7:9)
puma_gb_ceo <- extract_text(file = file_names_gb[39], pages = 18:19)
rheinmetall_gb_ceo <- ocr(image = file_names_gb[40])
rocketinternet_gb_ceo <- extract_text(file = file_names_gb[41], pages = 4:5)
salzgitter_gb_ceo <- extract_text(file = file_names_gb[42], pages = 5)
sartorius_gb_ceo <- extract_text(file = file_names_gb[43], pages = 10:11)
scout24_gb_ceo <- extract_text(file = file_names_gb[44], pages = 8:10)
siemenshealthineers_gb_ceo <- extract_text(file = file_names_gb[45], pages = 13:15)
siltronic_gb_ceo <- extract_text(file = file_names_gb[46], pages = 17:19)
softwareag_gb_ceo <- extract_text(file = file_names_gb[47], pages = 8:9)
symrise_gb_ceo <- extract_text(file = file_names_gb[48], pages = 10)
tag_gb_ceo <- extract_text(file = file_names_gb[49], pages = 3:4)
telefonica_gb_ceo <- extract_text(file = file_names_gb[50], pages = 6:7)
uniper_gb_ceo <- extract_text(file = file_names_gb[51], pages = 6:7)
unitedinternet_gb_ceo <- extract_text(file = file_names_gb[52], pages = 6:7)
wackerchemie_gb_ceo <- extract_text(file = file_names_gb[53], pages = 31:34)
zalando_gb_ceo <- extract_text(file = file_names_gb[54], pages = 10:11)

